### ISSUE TITLE
leveldiagram dependency not documented

### ISSUE THREAD

**Issue by petermao** [QTC-UMD/rydiqule#16]
needed to `pip install leveldiagram`.

**Comment by dihm** [comment]
All installation dependencies are documented in `setup.cfg`. Unfortunately, they are only enforced during pip installation of the package which typically is not done when updating an editable install from source. To get updated dependencies in the future, be sure to re-run the editable install command once your local repo has updated (i.e. `pip install -U -e .`).

**Comment by petermao** [comment]
ok, thanks.  perhaps the `-U` option should be mentioned in the docs for this reason.

**Comment by dihm** [comment]
Ah, my apologies. That `-U` is only there as a force of personal habit. You don't actually need it to grab new or updated required dependencies (just doing a normal pip install accomplishes that, so `pip install -e .`). 

The pip upgrade option just tells pip to be greedy and update any and all related packages to their latest releases, in excess of the package requirements. I do it so I can keep up with dependency packages and try to fix deprecations early. Honestly probably not a great idea for the regular rydiqule user.
