### ISSUE TITLE
incompatibility with numpy version >= 2.0.0

### ISSUE THREAD

**Issue by evgmik** [QTC-UMD/rydiqule#22]
Hi in version 2.0.0 and onward `numpy` modified several functions and in particular  'meshgrid' logic which returns a `tuple` instead of a `list`: see https://github.com/numpy/numpy/pull/25570 this breaks logic at https://github.com/QTC-UMD/rydiqule/blob/87d136e3895880a8c6fa58c4c5f2546fb1660069/src/rydiqule/sensor.py#L1304  and raises `AttributeError: 'tuple' object has no attribute 'copy'` with `numpy` vetsion >= 2.0.0

Two potential fixes: 
- freeze required version of `numpy` at the last version before 2.0.0 version, aka v1.26.4 (tested and its works).
-  modify the code to be compatible with new `numpy`.  Unfortunately, the later requires more work then just siple `tuple` to `list` conversion in above place, since linear equation solver stop working too with old list types.

**Comment by dihm** [comment]
And here I thought we were clear of these compatibility issues once ARC became v2 compatible. Thank you for the report @evgmik!

In any case, we have been doing significant development for v2 of rydiqule, and we've actually removed this particular call already. We hope to have v2 ready to release before the end of the year, and we'll be sure to check for other numpy v2 compatibility issues with the new release before then.

In the meantime, I recommend manually downgrading numpy.

**Comment by evgmik** [comment]
Would it be possible to lock numpy version in `setup.cfg` and upload the package to pip? This way the `pip install` will do the right job before the major update is realeased. It took me a while to find a bug, I am sure, it will ease up the life of people less fluent in intricate software dependencies.

**Comment by dihm** [comment]
@evgmik I have published a patch v1.2.3 which updates a few version pins to avoid issues with incompatibilities in newer dependency versions.
